// Auto-generated API documentation from the library
// This file is generated by scripts/generate-api-docs.ts
// DO NOT EDIT MANUALLY - run: bun run generate:api-docs

import type { ReliableScheduler } from "../../src/index";

export const API_METHODS = [
  {
    name: "constructor",
    signature: "new ReliableScheduler(storage: DurableObjectStorage)",
    description: "Creates a new scheduler instance with the provided Durable Object storage.",
    type: "constructor" as const,
  },
  {
    name: "generateTaskId",
    signature: "static generateTaskId(prefix: string = \"task\"): string",
    description: "Generate a unique task ID. Default prefix is 'task'.",
    type: "static" as const,
  },
  {
    name: "alarm",
    signature: "async alarm(): Promise<void>",
    description: "Call this from your Durable Object's alarm handler to process scheduled tasks.",
    type: "method" as const,
  },
  {
    name: "cancelTask",
    signature: "async cancelTask(taskId: string): Promise<boolean>",
    description: "Cancel and delete a task. Returns true if successful, false if task not found.",
    type: "method" as const,
  },
  {
    name: "checkpoint",
    signature: "async checkpoint(taskId: string, key: string, value: unknown): Promise<void>",
    description: "Save progress for a task. Use this to mark completion of expensive operations.",
    type: "method" as const,
  },
  {
    name: "clearAll",
    signature: "async clearAll(): Promise<number>",
    description: "Delete all tasks regardless of status. Returns the count of deleted tasks.",
    type: "method" as const,
  },
  {
    name: "clearCompleted",
    signature: "async clearCompleted(): Promise<number>",
    description: "Delete all completed tasks. Returns the count of deleted tasks.",
    type: "method" as const,
  },
  {
    name: "completeTask",
    signature: "async completeTask(taskId: string): Promise<void>",
    description: "Mark a task as complete and clean up its state.",
    type: "method" as const,
  },
  {
    name: "formatTaskForUI",
    signature: "formatTaskForUI(task: Task): any",
    description: "Format a task object for UI consumption with standardized fields.",
    type: "method" as const,
  },
  {
    name: "getCheckpoint",
    signature: "async getCheckpoint(taskId: string, key: string): Promise<unknown>",
    description: "Retrieve saved progress for a task. Returns undefined if not found.",
    type: "method" as const,
  },
  {
    name: "getHandler",
    signature: "getHandler(taskName: string): TaskHandler | undefined",
    description: "Get a registered handler by name. Returns undefined if not found.",
    type: "method" as const,
  },
  {
    name: "getTask",
    signature: "async getTask(taskId: string): Promise<Task | undefined>",
    description: "Get a single task by ID. Returns undefined if not found.",
    type: "method" as const,
  },
  {
    name: "getTasks",
    signature: "async getTasks(status?: TaskStatus): Promise<Task[]>",
    description: "Get all tasks, optionally filtered by status.",
    type: "method" as const,
  },
  {
    name: "pauseTask",
    signature: "async pauseTask(taskId: string): Promise<boolean>",
    description: "Pause a running task. Returns true if successful, false if task not found or cannot be paused.",
    type: "method" as const,
  },
  {
    name: "register",
    signature: "register(taskName: string, handler: TaskHandler): void",
    description: "Register a named task handler. The handler receives the scheduler, taskId, and params.",
    type: "method" as const,
  },
  {
    name: "resumeTask",
    signature: "async resumeTask(taskId: string): Promise<boolean>",
    description: "Resume a paused task. Returns true if successful, false if task not found or not paused.",
    type: "method" as const,
  },
  {
    name: "runNow",
    signature: "async runNow((): Promise<void>",
    description: "Start a task immediately with eviction safety. Sets a 30s safety alarm for automatic retry. @param options.maxRetries - Override default retry count (default: 3, use Infinity for infinite loop tasks)",
    type: "method" as const,
  },
  {
    name: "runSteps",
    signature: "async runSteps((): Promise<void>",
    description: "Execute a multi-step task with automatic progress tracking, pause/resume support, checkpointing, and optional auto-completion.",
    type: "method" as const,
  },
  {
    name: "runSubSteps",
    signature: "async runSubSteps(taskId: string, stepName: string, stepIndex: number, totalSteps: number, subStepCount: number, subStepDuration: number, onSubStep?: (subStepIndex: number) => Promise<void> | Effect.Effect<void>): Promise<void>",
    description: "Helper for sub-step execution within a step. Handles pause checks and progress tracking automatically.",
    type: "method" as const,
  },
  {
    name: "schedule",
    signature: "async schedule((): Promise<void>",
    description: "Schedule a task to run at a future time (Unix timestamp or Date).",
    type: "method" as const,
  }
] as const;
